name: radio_skonto
description: "Radio Skonto App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.18+48

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  #easy_localization: ^3.0.7
  shared_preferences: ^2.2.3
  persistent_bottom_nav_bar: ^6.2.1
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.0
  flutter_switch: ^0.3.2
  connectivity_plus: ^6.1.0
  internet_connection_checker_plus: ^2.5.2
  get: ^4.6.6
  audio_service: ^0.18.15
  just_audio: ^0.9.38
  provider: ^6.1.2
  circle_flags: ^5.0.0
  rxdart: ^0.27.2
  flutter_bloc: ^8.1.3
  go_router: ^13.2.4
  cached_network_image: ^3.3.1
  modal_bottom_sheet: ^3.0.0-pre
  flutter_markdown: ^0.6.20+1
#  scroll_snap_list: ^0.9.1
  share_plus: ^10.0.0
  contained_tab_bar_view: ^0.8.0
  sticky_headers: ^0.3.0+2
  video_player: ^2.9.1
  chewie: ^1.8.3
  flutter_widget_from_html: ^0.15.3
  styled_text: ^8.1.0
  carousel_slider: ^5.0.0
  infinite_carousel: ^1.1.1
#  flutter_sms: ^2.3.3
#  flutter_carplay: ^1.0.3
  flutter_carplay:
    git:
      url: https://github.com/icapps/flutter_carplay.git # Where to find Repo
      ref: combine-all # branch name
  device_info_plus: ^10.1.2
  flutter_staggered_grid_view: ^0.7.0
  path_provider: ^2.1.4
  shimmer: ^3.0.0
  flutter_downloader: ^1.11.8
  permission_handler: ^11.3.1
  infinity_page_view_astro: ^1.0.0
  visibility_detector: ^0.4.0+2
  youtube_player_flutter: ^8.1.2
  flutter_inappwebview: ^5.8.0
  volume_controller: ^2.0.8
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translations/
    - assets/icons/radio_icon.svg
    - assets/icons/microphone.svg
    - assets/icons/music.svg
    - assets/icons/pressent.svg
    - assets/icons/alarm_icon.svg
    - assets/icons/heart_icon.svg
    - assets/icons/burger_icon.svg
    - assets/icons/logout_icon.svg
    - assets/image/skonto_logo_svg.svg
    - assets/icons/log_in_icon.svg
    - assets/image/instruction_one.png
    - assets/image/instruction_two.png
    - assets/image/instruction_three.png
    - assets/image/main_icon.png
    - assets/icons/button_play.svg
    - assets/icons/volume_icon.svg
    - assets/icons/play_button_big.svg
    - assets/icons/dislike_icon.svg
    - assets/icons/like_icon.svg
    - assets/icons/three_dot_button.svg
    - assets/icons/pause_button.svg
    - assets/icons/pause_button_big.svg
    - assets/image/skonto_logo_for_radio_list.png
    - assets/icons/copy_icon.svg
    - assets/icons/email_icon.svg
    - assets/icons/instagram_icon.svg
    - assets/icons/facebook_icon.svg
    - assets/icons/whatsapp_icon.svg
    - assets/icons/filters_icon.svg
    - assets/icons/heart_for_button_icon.svg
    - assets/icons/download_icon.svg
    - assets/icons/shared_video.svg
    - assets/icons/heart_not_empty.svg
    - assets/image/phone_button.svg
    - assets/image/button_sms.svg
    - assets/image/button_email.svg
    - assets/image/button_whats_app.svg
    - assets/image/facebook_icon_round.svg
    - assets/image/instagramm_icon_round.svg
    - assets/image/lincendin_icon_round.svg
    - assets/image/tic_toc_icon_round.svg
    - assets/image/x_icon_round.svg
    - assets/logo_flutter_1080px_clr.png
    - assets/icons/arrow_left.svg
    - assets/icons/arrow_right.svg
    - assets/icons/close_icon.svg
    - assets/image/background_image.png
    - assets/icons/check_icon.svg
    - assets/icons/hide_password.svg
    - assets/icons/show_password.svg
    - assets/icons/row_down.svg
    - assets/image/LOUNGE_FM.png
    - assets/image/RADIO_SKONTO.png
    - assets/image/RADIO_SKONTO_PLUS.png
    - assets/image/RADIO_TEV.png
    - assets/image/TEV_LV.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CustomAppIconsBars
      fonts:
        - asset: assets/icons/CustomAppIconsBars.ttf
    - family: 'Raleway'
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf
        - asset: assets/fonts/Raleway-Regular.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
